# version: "3.9"

networks:
  volunteerhub-net:
    driver: bridge

services:
  mongo:
    image: mongo:6
    container_name: volunteer-mongo
    ports:
      - "27017:27017"
    networks:
      - volunteerhub-net
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - volunteerhub-net
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - volunteerhub-net
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4002:4002"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    env_file:
      - ./notification-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4004:4004"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped

  event-service:
    build:
      context: .
      dockerfile: event-service/Dockerfile
    container_name: event-service
    env_file:
      - ./event-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4006:4006"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped
  event-registration-service:
    build:
      context: .
      dockerfile: event-registration-service/Dockerfile
    container_name: event-registration-service
    env_file:
      - ./event-registration-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4008:4008"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped
  
  communication-service:
    build:
      context: .
      dockerfile: communication-service/Dockerfile
    container_name: communication-service
    env_file:
      - ./communication-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4010:4010"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped

  dashboard-service:
    build:
      context: .
      dockerfile: dashboard-service/Dockerfile
    container_name: dashboard-service
    env_file:
      - ./dashboard-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4012:4012"
    depends_on:
      - mongo
      - redis
      - rabbitmq
    restart: unless-stopped


  kong:
    image: kong:3.5
    container_name: kong
    networks:
      - volunteerhub-net
    depends_on:
      - auth-service
      - user-service
      - communication-service
      - dashboard-service
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    restart: unless-stopped

volumes:
  rabbitmq-data:
