version: '3.9'

networks:
  volunteerhub-net:
    driver: bridge

services:
  # MongoDB cho các service
  mongo:
    image: mongo:6
    container_name: volunteer-mongo
    ports:
      - "27017:27017"
    networks:
      - volunteerhub-net
    restart: unless-stopped

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - volunteerhub-net
    restart: unless-stopped

  # Auth-service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  # User-service
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    env_file:
      - ./user-service/.env
    networks:
      - volunteerhub-net
    ports:
      - "4002:4002"
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    environment:
      - JWT_ACCESS_SECRET=your_super_secret_key
      - JWT_REFRESH_SECRET=your_refresh_secret_key
      - MONGO_URI=mongodb://volunteer-mongo:27017/user-service

  # Kong Gateway (DB-less mode)
  kong:
    image: kong:3.5
    container_name: kong
    networks:
      - volunteerhub-net
    depends_on:
      - auth-service
      - user-service
    ports:
      - "8000:8000"   # proxy
      - "8001:8001"   # admin
    environment:
      KONG_DATABASE: "off"  # DB-less mode
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    restart: unless-stopped
