###
POST http://localhost:4008/registrations/apply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2ZTE1ODg4ZjcyYWZhNzE1YjBhZDMiLCJlbWFpbCI6ImhlaGVAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6bnVsbCwicm9sZUlkIjoiNjkzNjhjNjA5NDYxOTMzM2EyMTAwMTEzIiwicm9sZU5hbWUiOiJ2b2x1bnRlZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpyZWFkIiwicmVnaXN0cmF0aW9uOmNyZWF0ZSIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmNhbmNlbCIsInBvc3Q6cmVhZCIsInBvc3Q6Y3JlYXRlIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyJdLCJpYXQiOjE3NjUyMDQzMTQsImV4cCI6MTc2NTIwNTIxNH0.YTqelOVIatFXugHycr3kVEGAkjjjjS7U4KeOy4w-dkc
Content-Type: application/json

{
  "eventId": "693697e7f809bc9c8ede743b",
  "roleId": "29520a16-3bd6-48ac-90e0-80412310201b",
  "motivation": "I want to help because I have experience volunteering in several community events and I am passionate about supporting people in need.",
  "skills": ["first aid", "organizing"],
  "availability": "weekends",
  "experience": "2 years volunteering",
  "emergencyContact": {
    "name": "John Doe",
    "phone": "0123456789",
    "relationship": "Friend"
  }
}

###
PUT http://localhost:4008/registrations/6936e16ccfaf9a63064e71ec/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2OGM2MTk0NjE5MzMzYTIxMDAxMjAiLCJlbWFpbCI6InRsaW5oX21hbmFnZXJAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCBNYW5hZ2VyIiwicGhvbmVOdW1iZXIiOiIrODQ5MDk4NzY1NDMiLCJyb2xlSWQiOiI2OTM2OGM2MDk0NjE5MzMzYTIxMDAxMTIiLCJyb2xlTmFtZSI6ImV2ZW50X21hbmFnZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpjcmVhdGUiLCJldmVudDpyZWFkIiwiZXZlbnQ6dXBkYXRlIiwiZXZlbnQ6ZGVsZXRlIiwiZXZlbnQ6YXBwcm92ZSIsImV2ZW50OnJlamVjdCIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmFwcHJvdmUiLCJyZWdpc3RyYXRpb246bWFya19jb21wbGV0ZSIsInBvc3Q6Y3JlYXRlIiwicG9zdDpyZWFkIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyIsInJlcG9ydDp2aWV3IiwicmVwb3J0OmV4cG9ydCJdLCJpYXQiOjE3NjUyMDQzNTcsImV4cCI6MTc2NTIwNTI1N30.D8vQ8Zj5_2NPyrsfw2bFH7fQ7Rb3Mwj3RLYQaUGJHVc
Content-Type: application/json

{

}

###
PUT http://localhost:4008/registrations/6936e16ccfaf9a63064e71ec/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2ZTE1ODg4ZjcyYWZhNzE1YjBhZDMiLCJlbWFpbCI6ImhlaGVAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6bnVsbCwicm9sZUlkIjoiNjkzNjhjNjA5NDYxOTMzM2EyMTAwMTEzIiwicm9sZU5hbWUiOiJ2b2x1bnRlZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpyZWFkIiwicmVnaXN0cmF0aW9uOmNyZWF0ZSIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmNhbmNlbCIsInBvc3Q6cmVhZCIsInBvc3Q6Y3JlYXRlIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyJdLCJpYXQiOjE3NjUyMDQzMTQsImV4cCI6MTc2NTIwNTIxNH0.YTqelOVIatFXugHycr3kVEGAkjjjjS7U4KeOy4w-dkc
