###
POST http://localhost:4008/registrations/apply
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1YzZlMDc4ODYwN2ZmMWQwY2ZmOTUiLCJlbWFpbCI6InRsaW5obmdvb3MxQGdtYWlsLmNvbSIsIm5hbWUiOiJOZ3V5ZW4gVGh1eSBMaW5oIiwicGhvbmVOdW1iZXIiOm51bGwsInJvbGVJZCI6IjY5MzVjM2QwNTJiMjAwZGNhODIxZjczOCIsInJvbGVOYW1lIjoidm9sdW50ZWVyIiwicGVybWlzc2lvbnMiOlsiZXZlbnQ6cmVhZCIsInJlZ2lzdHJhdGlvbjpjcmVhdGUiLCJyZWdpc3RyYXRpb246cmVhZCIsInJlZ2lzdHJhdGlvbjpjYW5jZWwiLCJwb3N0OnJlYWQiLCJwb3N0OmNyZWF0ZSIsInBvc3Q6dXBkYXRlOm93biIsInBvc3Q6ZGVsZXRlOm93biIsImNvbW1lbnQ6Y3JlYXRlIiwiZGFzaGJvYXJkOnZpZXciXSwiaWF0IjoxNzY1MTMyMDA1LCJleHAiOjE3NjUxMzI5MDV9.ZWJtvfY6CI3VrXSzS1W0FBoZbmKid_ZNhm8gKrWTzUM
Content-Type: application/json

{
  "eventId": "6935c411357a2bb5467893e2",
  "roleId": "d0633946-06ec-4648-af09-62e4bd5d3b09",
  "motivation": "I want to help because I have experience volunteering in several community events and I am passionate about supporting people in need.",
  "skills": ["first aid", "organizing"],
  "availability": "weekends",
  "experience": "2 years volunteering",
  "emergencyContact": {
    "name": "John Doe",
    "phone": "0123456789",
    "relationship": "Friend"
  }
}

###
PUT http://localhost:4008/registrations/6935c6f52e73a030f96ea3a4/accept
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1YzNkMDUyYjIwMGRjYTgyMWY3NDIiLCJlbWFpbCI6InRsaW5oX21hbmFnZXJAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCBNYW5hZ2VyIiwicGhvbmVOdW1iZXIiOiIrODQ5MDk4NzY1NDMiLCJyb2xlSWQiOiI2OTM1YzNkMDUyYjIwMGRjYTgyMWY3MzciLCJyb2xlTmFtZSI6ImV2ZW50X21hbmFnZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpjcmVhdGUiLCJldmVudDpyZWFkIiwiZXZlbnQ6dXBkYXRlIiwiZXZlbnQ6ZGVsZXRlIiwiZXZlbnQ6YXBwcm92ZSIsImV2ZW50OnJlamVjdCIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmFwcHJvdmUiLCJyZWdpc3RyYXRpb246bWFya19jb21wbGV0ZSIsInBvc3Q6Y3JlYXRlIiwicG9zdDpyZWFkIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyIsInJlcG9ydDp2aWV3IiwicmVwb3J0OmV4cG9ydCJdLCJpYXQiOjE3NjUxMzIwNDUsImV4cCI6MTc2NTEzMjk0NX0.8_cY852kryw7-idRWjHTFh-5YlLk5Rqe41cvTl6Rr9k
Content-Type: application/json

{

}

###
PUT http://localhost:4008/registrations/6935c6f52e73a030f96ea3a4/confirm
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1YzZlMDc4ODYwN2ZmMWQwY2ZmOTUiLCJlbWFpbCI6InRsaW5obmdvb3MxQGdtYWlsLmNvbSIsIm5hbWUiOiJOZ3V5ZW4gVGh1eSBMaW5oIiwicGhvbmVOdW1iZXIiOm51bGwsInJvbGVJZCI6IjY5MzVjM2QwNTJiMjAwZGNhODIxZjczOCIsInJvbGVOYW1lIjoidm9sdW50ZWVyIiwicGVybWlzc2lvbnMiOlsiZXZlbnQ6cmVhZCIsInJlZ2lzdHJhdGlvbjpjcmVhdGUiLCJyZWdpc3RyYXRpb246cmVhZCIsInJlZ2lzdHJhdGlvbjpjYW5jZWwiLCJwb3N0OnJlYWQiLCJwb3N0OmNyZWF0ZSIsInBvc3Q6dXBkYXRlOm93biIsInBvc3Q6ZGVsZXRlOm93biIsImNvbW1lbnQ6Y3JlYXRlIiwiZGFzaGJvYXJkOnZpZXciXSwiaWF0IjoxNzY1MTMyMDA1LCJleHAiOjE3NjUxMzI5MDV9.ZWJtvfY6CI3VrXSzS1W0FBoZbmKid_ZNhm8gKrWTzUM
Content-Type: application/json

{

}
