### EVENT CATEGORY

### lấy tất các loại sự kiện (có thể là mặc định hoặc do admin tạo
GET http://localhost:8000/categories?activeOnly=true
Accept: application/json


### Get category by ID (PUBLIC) - lấy thông tin của loại sự kiện theo id (69353497dca8945bda8b8318 là id của loại sự kiện đó)
GET http://localhost:8000/categories/69353497dca8945bda8b8318
Accept: application/json


### Create category (ADMIN) - tạo một loại sự kiện mới do admin tạo
### Authorization: Bearer <admin access token>
POST http://localhost:8000/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM0NWY0NTlkZWJiMTA0ODM1YzM4ZTkiLCJlbWFpbCI6InRsaW5oQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6bnVsbCwicm9sZUlkIjoiNjkzNDVmNDU5ZGViYjEwNDgzNWMzOGRjIiwicm9sZU5hbWUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbIioiXSwiaWF0IjoxNzY1MDgwNzQzLCJleHAiOjE3NjUwODE2NDN9.GVW_ev_r1FWv7HkwlfuJPqOF5M0vHQmbGz4o24ecoYc

{
"name": "hehe",
"description": "Sports related events",
"icon": "i",
"color": "#FF5733",
"parentId": null,
"order": 5,
"isActive": true
}


### Update category (ADMIN) - cập nhận thông tin của loại sự kiện đó 
### 693537e1e17f21cc31027a3d - id của loại sự kiện đó
### Authorization: Bearer <admin access token>
PUT http://localhost:8000/categories/693537e1e17f21cc31027a3d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM0NWY0NTlkZWJiMTA0ODM1YzM4ZTkiLCJlbWFpbCI6InRsaW5oQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6bnVsbCwicm9sZUlkIjoiNjkzNDVmNDU5ZGViYjEwNDgzNWMzOGRjIiwicm9sZU5hbWUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbIioiXSwiaWF0IjoxNzY1MDgwNzQzLCJleHAiOjE3NjUwODE2NDN9.GVW_ev_r1FWv7HkwlfuJPqOF5M0vHQmbGz4o24ecoYc

{
"name": "Sports",
"color": "#33FF57"
}

### Delete category (ADMIN) - xóa loại sự kiện theo id
### Authorization: Bearer <admin access token>
DELETE http://localhost:8000/categories/693537e1e17f21cc31027a3d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1Mzc1NTA2MTc1OWYwNGY0ZmRhMWUiLCJlbWFpbCI6InRsaW5oQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6Iis4NDkwMTIzNDU2NyIsInJvbGVJZCI6IjY5MzUzNzU1MDYxNzU5ZjA0ZjRmZGExNiIsInJvbGVOYW1lIjoiYWRtaW4iLCJwZXJtaXNzaW9ucyI6WyIqIl0sImlhdCI6MTc2NTA5NTM2MSwiZXhwIjoxNzY1MDk2MjYxfQ.NqU0rYynT4TZl5lV5_73UYDlZB9qTgXD3Uaj4L7MYkU


### Seed default categories (ADMIN) - tạo các sự kiện mặc định - do admin tạo -- sẽ tạo sẵn trước nên ko cần gọi
### Authorization: Bearer <admin access token>
POST http://localhost:8000/categories/seed/default
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2OGM2MTk0NjE5MzMzYTIxMDAxMjAiLCJlbWFpbCI6InRsaW5oX21hbmFnZXJAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCBNYW5hZ2VyIiwicGhvbmVOdW1iZXIiOiIrODQ5MDk4NzY1NDMiLCJyb2xlSWQiOiI2OTM2OGM2MDk0NjE5MzMzYTIxMDAxMTIiLCJyb2xlTmFtZSI6ImV2ZW50X21hbmFnZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpjcmVhdGUiLCJldmVudDpyZWFkIiwiZXZlbnQ6dXBkYXRlIiwiZXZlbnQ6ZGVsZXRlIiwiZXZlbnQ6YXBwcm92ZSIsImV2ZW50OnJlamVjdCIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmFwcHJvdmUiLCJyZWdpc3RyYXRpb246bWFya19jb21wbGV0ZSIsInBvc3Q6Y3JlYXRlIiwicG9zdDpyZWFkIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyIsInJlcG9ydDp2aWV3IiwicmVwb3J0OmV4cG9ydCJdLCJpYXQiOjE3NjUxODU0MjQsImV4cCI6MTc2NTE4NjMyNH0.34Nbt1Yi0hOULm66npeRyip05WBlxkxSDLRuyiOaPkw
Accept: appli



### EVENT

### List all published events (PUBLIC) - lấy danh sách tất cả các sự kiện - theo các filter
### filter: 
GET http://localhost:8000/events
Accept: application/json


### Get event by slug (PUBLIC) - lấy sự kiện theo slug (tên sự kiện nhưng theo kiểu cách nhau dấu gạch như này)
GET http://localhost:8000/events/slug/chu-nhat-xanh-cung-djai-hoc-cong-nghe
Accept: application/json


### các luồng có thể xảy ra
# export const EVENT_STATUS_TRANSITIONS = {
#     [EventStatus.DRAFT]: [EventStatus.PENDING_APPROVAL, EventStatus.CANCELLED], -- bên trái có thể chuyển qua các trạng thái bên phải
#     [EventStatus.PENDING_APPROVAL]: [EventStatus.APPROVED, EventStatus.REJECTED],
#     [EventStatus.APPROVED]: [EventStatus.PUBLISHED, EventStatus.CANCELLED],
#     [EventStatus.REJECTED]: [EventStatus.PENDING_APPROVAL, EventStatus.CANCELLED],
#     [EventStatus.PUBLISHED]: [EventStatus.ONGOING, EventStatus.CANCELLED],
#     [EventStatus.ONGOING]: [EventStatus.COMPLETED, EventStatus.CANCELLED],
#     [EventStatus.COMPLETED]: [],
#     [EventStatus.CANCELLED]: [],
# };


### Create Event - tạo một sự kiện - có thể do admin hoặc event-manager ( thường là event-manager tạo để admin duyệt)
### Authorization: Bearer <event-manager access token>
### sau khi gọi --> tạo bản draft --> status: DRAFT
POST http://localhost:8000/events
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4M2QyZGEwNDY1Mjc3YjcyNWFmZWIiLCJlbWFpbCI6ImR1b25naG9hbmdnMjYxQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmggTWFuYWdlciIsInBob25lTnVtYmVyIjoiKzg0OTA5ODc2NTQzIiwicm9sZUlkIjoiNjkzODNkMmNhMDQ2NTI3N2I3MjVhZmRjIiwicm9sZU5hbWUiOiJldmVudF9tYW5hZ2VyIiwicGVybWlzc2lvbnMiOlsiZXZlbnQ6Y3JlYXRlIiwiZXZlbnQ6cmVhZCIsImV2ZW50OnVwZGF0ZSIsImV2ZW50OmRlbGV0ZSIsImV2ZW50OmFwcHJvdmUiLCJldmVudDpyZWplY3QiLCJyZWdpc3RyYXRpb246cmVhZCIsInJlZ2lzdHJhdGlvbjphcHByb3ZlIiwicmVnaXN0cmF0aW9uOm1hcmtfY29tcGxldGUiLCJwb3N0OmNyZWF0ZSIsInBvc3Q6cmVhZCIsInBvc3Q6dXBkYXRlOm93biIsInBvc3Q6ZGVsZXRlOm93biIsImNvbW1lbnQ6Y3JlYXRlIiwiZGFzaGJvYXJkOnZpZXciLCJyZXBvcnQ6dmlldyIsInJlcG9ydDpleHBvcnQiXSwiaWF0IjoxNzY1MjkzMzg1LCJleHAiOjE3NjUyOTQyODV9.le-2gphOjsP0Nyf0RIL1fwDLYO7YbDQozdk0CJ8ZoIU

{
"title": "Chủ nhật xanh cùng đại học công nghệ",
"description": "Cùng nhau dọn dẹp vệ sinh môi trường, làm sạch công viên và bãi biển.",
"categoryId": "69383d7a900d6076ff2d8186",
"location": {
    "address": "Xuân Thủy - Hà Nội",
    "city": "Hà Nội",
    "district": "Cầu Giấy"
},
"schedule": {
    "startDate": "2025-12-20T07:00:00.000Z",
    "endDate": "2025-12-20T11:00:00.000Z",
    "registrationDeadline": "2025-12-18T23:59:59.000Z"
},
"requirements": {
    "minAge": 16,
    "maxAge": 60,
    "skills": ["Làm việc nhóm","Chăm chỉ"],
    "experience": "Không yêu cầu kinh nghiệm",
    "healthRequirements": "Sức khỏe tốt"
},
"capacity": {
    "maxVolunteers": 50,
    "minVolunteers": 10
},
"roles": [
    { "name": "Nhóm trưởng", "description": "Điều phối nhóm 5-10 người", "slots": 5 },
    { "name": "Tình nguyện viên", "description": "Thu gom rác", "slots": 45 }
],
"images": [ "https://cdn.example.com/events/green-sunday-cover.jpg" ],
"videos": [ "https://cdn.example.com/events/green-sunday-cover.jpg" ],
"visibility": "public",
"tags": ["xanh", "sinh viên"]
}

### Update event (ORGANIZER/ADMIN) - có thể sửa khi status là draft -- người tạo mới có thể sửa nhaa
### Authorization: Bearer <event-manager access token>
PUT http://localhost:8000/events/69353854e17f21cc31027a4a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4M2QyZGEwNDY1Mjc3YjcyNWFmZWIiLCJlbWFpbCI6ImR1b25naG9hbmdnMjYxQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmggTWFuYWdlciIsInBob25lTnVtYmVyIjoiKzg0OTA5ODc2NTQzIiwicm9sZUlkIjoiNjkzODNkMmNhMDQ2NTI3N2I3MjVhZmRjIiwicm9sZU5hbWUiOiJldmVudF9tYW5hZ2VyIiwicGVybWlzc2lvbnMiOlsiZXZlbnQ6Y3JlYXRlIiwiZXZlbnQ6cmVhZCIsImV2ZW50OnVwZGF0ZSIsImV2ZW50OmRlbGV0ZSIsImV2ZW50OmFwcHJvdmUiLCJldmVudDpyZWplY3QiLCJyZWdpc3RyYXRpb246cmVhZCIsInJlZ2lzdHJhdGlvbjphcHByb3ZlIiwicmVnaXN0cmF0aW9uOm1hcmtfY29tcGxldGUiLCJwb3N0OmNyZWF0ZSIsInBvc3Q6cmVhZCIsInBvc3Q6dXBkYXRlOm93biIsInBvc3Q6ZGVsZXRlOm93biIsImNvbW1lbnQ6Y3JlYXRlIiwiZGFzaGJvYXJkOnZpZXciLCJyZXBvcnQ6dmlldyIsInJlcG9ydDpleHBvcnQiXSwiaWF0IjoxNzY1MjkzMzg1LCJleHAiOjE3NjUyOTQyODV9.le-2gphOjsP0Nyf0RIL1fwDLYO7YbDQozdk0CJ8ZoIU

{
    "title": "Chủ nhật xanh cùng Ký túc xá Mỹ Đình - cập nhật",
    "description": "Cùng nhau dọn dẹp vệ sinh môi trường, làm sạch công viên và bãi biển. Cập nhật nội dung.",
    "location": {
        "address": "Xuân Thủy - Hà Nội",
        "city": "Hà Nội",
        "district": "Cầu Giấy"
    },
    "tags": ["xanh", "sinh viên", "môi trường"]
}


### Submit event for approval (ORGANIZER) -- submit để admin duyệt event
### Authorization: Bearer <event-manager access token>
### status: PENDING_APPROVAL (chờ duyệt)
POST http://localhost:8000/events/69383ed9900d6076ff2d819f/submit
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4M2QyZGEwNDY1Mjc3YjcyNWFmZWIiLCJlbWFpbCI6ImR1b25naG9hbmdnMjYxQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmggTWFuYWdlciIsInBob25lTnVtYmVyIjoiKzg0OTA5ODc2NTQzIiwicm9sZUlkIjoiNjkzODNkMmNhMDQ2NTI3N2I3MjVhZmRjIiwicm9sZU5hbWUiOiJldmVudF9tYW5hZ2VyIiwicGVybWlzc2lvbnMiOlsiZXZlbnQ6Y3JlYXRlIiwiZXZlbnQ6cmVhZCIsImV2ZW50OnVwZGF0ZSIsImV2ZW50OmRlbGV0ZSIsImV2ZW50OmFwcHJvdmUiLCJldmVudDpyZWplY3QiLCJyZWdpc3RyYXRpb246cmVhZCIsInJlZ2lzdHJhdGlvbjphcHByb3ZlIiwicmVnaXN0cmF0aW9uOm1hcmtfY29tcGxldGUiLCJwb3N0OmNyZWF0ZSIsInBvc3Q6cmVhZCIsInBvc3Q6dXBkYXRlOm93biIsInBvc3Q6ZGVsZXRlOm93biIsImNvbW1lbnQ6Y3JlYXRlIiwiZGFzaGJvYXJkOnZpZXciLCJyZXBvcnQ6dmlldyIsInJlcG9ydDpleHBvcnQiXSwiaWF0IjoxNzY1MjkzMzg1LCJleHAiOjE3NjUyOTQyODV9.le-2gphOjsP0Nyf0RIL1fwDLYO7YbDQozdk0CJ8ZoIU

# sau khi event-manager submit --> chuyển qua admin để chấp nhận hoặc từ chối
### Approve event (ADMIN)
### status: APPROVED
### Authorization: Bearer <admin access token>
POST http://localhost:8000/events/69383d86900d6076ff2d8192/approve
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4M2QyY2EwNDY1Mjc3YjcyNWFmZTciLCJlbWFpbCI6Im5ndXllbnRodXlsaW5oMjYwMTIwMDVAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCIsInBob25lTnVtYmVyIjoiKzg0OTAxMjM0NTY3Iiwicm9sZUlkIjoiNjkzODNkMmNhMDQ2NTI3N2I3MjVhZmRiIiwicm9sZU5hbWUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbIioiXSwiaWF0IjoxNzY1MjkzNTYxLCJleHAiOjE3NjUyOTQ0NjF9.4MV9iw9hnTMIPDST-rDdXQV3ekaXHFsevVTz0OfEyWo


### Reject event (ADMIN) 
### status: REJECTED
### Authorization: Bearer <admin access token>
POST http://localhost:8000/events/69383ed9900d6076ff2d819f/reject
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4M2QyY2EwNDY1Mjc3YjcyNWFmZTciLCJlbWFpbCI6Im5ndXllbnRodXlsaW5oMjYwMTIwMDVAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCIsInBob25lTnVtYmVyIjoiKzg0OTAxMjM0NTY3Iiwicm9sZUlkIjoiNjkzODNkMmNhMDQ2NTI3N2I3MjVhZmRiIiwicm9sZU5hbWUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbIioiXSwiaWF0IjoxNzY1MjkzNTYxLCJleHAiOjE3NjUyOTQ0NjF9.4MV9iw9hnTMIPDST-rDdXQV3ekaXHFsevVTz0OfEyWo

{
    "rejectionReason": "Missing key information"
}

###
### Publish event (ORGANIZER/ADMIN) - sự kiện bắt đầu đăng ký được
### Authorization: Bearer <event-maanger access token>
POST http://localhost:8000/events/693697e7f809bc9c8ede743b/publish
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM2OGM2MTk0NjE5MzMzYTIxMDAxMjAiLCJlbWFpbCI6InRsaW5oX21hbmFnZXJAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCBNYW5hZ2VyIiwicGhvbmVOdW1iZXIiOiIrODQ5MDk4NzY1NDMiLCJyb2xlSWQiOiI2OTM2OGM2MDk0NjE5MzMzYTIxMDAxMTIiLCJyb2xlTmFtZSI6ImV2ZW50X21hbmFnZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpjcmVhdGUiLCJldmVudDpyZWFkIiwiZXZlbnQ6dXBkYXRlIiwiZXZlbnQ6ZGVsZXRlIiwiZXZlbnQ6YXBwcm92ZSIsImV2ZW50OnJlamVjdCIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmFwcHJvdmUiLCJyZWdpc3RyYXRpb246bWFya19jb21wbGV0ZSIsInBvc3Q6Y3JlYXRlIiwicG9zdDpyZWFkIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyIsInJlcG9ydDp2aWV3IiwicmVwb3J0OmV4cG9ydCJdLCJpYXQiOjE3NjUxODU0MjQsImV4cCI6MTc2NTE4NjMyNH0.34Nbt1Yi0hOULm66npeRyip05WBlxkxSDLRuyiOaPkw


###
### Cancel event (ORGANIZER/ADMIN) - hủy sự kiện như luồng bên trên
### Authorization: Bearer <event-maanger access token>
POST http://localhost:8000/events/6938303dc915113317c392bd/cancel
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4MjUzMDBjMDlhOGEwY2Y5ZGRmMWMiLCJlbWFpbCI6InRsaW5oX21hbmFnZXJAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCBNYW5hZ2VyIiwicGhvbmVOdW1iZXIiOiIrODQ5MDk4NzY1NDMiLCJyb2xlSWQiOiI2OTM4MjUzMDBjMDlhOGEwY2Y5ZGRmMTEiLCJyb2xlTmFtZSI6ImV2ZW50X21hbmFnZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpjcmVhdGUiLCJldmVudDpyZWFkIiwiZXZlbnQ6dXBkYXRlIiwiZXZlbnQ6ZGVsZXRlIiwiZXZlbnQ6YXBwcm92ZSIsImV2ZW50OnJlamVjdCIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmFwcHJvdmUiLCJyZWdpc3RyYXRpb246bWFya19jb21wbGV0ZSIsInBvc3Q6Y3JlYXRlIiwicG9zdDpyZWFkIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyIsInJlcG9ydDp2aWV3IiwicmVwb3J0OmV4cG9ydCJdLCJpYXQiOjE3NjUyOTEyMjQsImV4cCI6MTc2NTI5MjEyNH0.x4G_4grxyLkG1CHN0qjEHPit3Bdd5Nyezn0EgPrTIH4

{
"cancellationReason": "Unexpected situation"
}

###
### Delete event (ORGANIZER/ADMIN)
#  Only DRAFT or REJECTED can be deleted
### Authorization: Bearer <admin access token>
### Authorization: Bearer <event-manager access token>
DELETE http://localhost:8000/events/6935a83b10323954d7a4dcc8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1Mzc1NTA2MTc1OWYwNGY0ZmRhMWUiLCJlbWFpbCI6InRsaW5oQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6Iis4NDkwMTIzNDU2NyIsInJvbGVJZCI6IjY5MzUzNzU1MDYxNzU5ZjA0ZjRmZGExNiIsInJvbGVOYW1lIjoiYWRtaW4iLCJwZXJtaXNzaW9ucyI6WyIqIl0sImlhdCI6MTc2NTA5OTA0NSwiZXhwIjoxNzY1MDk5OTQ1fQ.dt05Kj9YJ718Gnvtu6SJMydvUZLClp1tFFPo8yVLA5g

###

### Get my events (ORGANIZER/ADMIN) -- lấy danh sách event của mình
### Authorization: Bearer <event-manager access token>
GET http://localhost:8000/events/my/list
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1Mzc1NjA2MTc1OWYwNGY0ZmRhMjIiLCJlbWFpbCI6InRsaW5oX21hbmFnZXJAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCBNYW5hZ2VyIiwicGhvbmVOdW1iZXIiOiIrODQ5MDk4NzY1NDMiLCJyb2xlSWQiOiI2OTM1Mzc1NTA2MTc1OWYwNGY0ZmRhMTciLCJyb2xlTmFtZSI6ImV2ZW50X21hbmFnZXIiLCJwZXJtaXNzaW9ucyI6WyJldmVudDpjcmVhdGUiLCJldmVudDpyZWFkIiwiZXZlbnQ6dXBkYXRlIiwiZXZlbnQ6ZGVsZXRlIiwiZXZlbnQ6YXBwcm92ZSIsImV2ZW50OnJlamVjdCIsInJlZ2lzdHJhdGlvbjpyZWFkIiwicmVnaXN0cmF0aW9uOmFwcHJvdmUiLCJyZWdpc3RyYXRpb246bWFya19jb21wbGV0ZSIsInBvc3Q6Y3JlYXRlIiwicG9zdDpyZWFkIiwicG9zdDp1cGRhdGU6b3duIiwicG9zdDpkZWxldGU6b3duIiwiY29tbWVudDpjcmVhdGUiLCJkYXNoYm9hcmQ6dmlldyIsInJlcG9ydDp2aWV3IiwicmVwb3J0OmV4cG9ydCJdLCJpYXQiOjE3NjUwOTkyMzQsImV4cCI6MTc2NTEwMDEzNH0.XGPf_Ym78Ej3X1wTToGn2A1s2lYGtMXr_mXGezNTSWg
Accept: application/json

###

### Get pending approval events (ADMIN) -- lấy sanh sách các event cần duyệt
GET http://localhost:8000/events/admin/pending
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM4M2QyY2EwNDY1Mjc3YjcyNWFmZTciLCJlbWFpbCI6Im5ndXllbnRodXlsaW5oMjYwMTIwMDVAZ21haWwuY29tIiwibmFtZSI6IlRodXkgTGluaCIsInBob25lTnVtYmVyIjoiKzg0OTAxMjM0NTY3Iiwicm9sZUlkIjoiNjkzODNkMmNhMDQ2NTI3N2I3MjVhZmRiIiwicm9sZU5hbWUiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbIioiXSwiaWF0IjoxNzY1MjkzNzM4LCJleHAiOjE3NjUyOTQ2Mzh9.NHGHDAnFH_CwOeuSmdmjAFYIKRqOcnxN5fRJhZhJMXY
Accept: application/json

###

### Get event statistics (ADMIN) - tổng hợp
GET http://localhost:8000/events/admin/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTM1Mzc1NTA2MTc1OWYwNGY0ZmRhMWUiLCJlbWFpbCI6InRsaW5oQGdtYWlsLmNvbSIsIm5hbWUiOiJUaHV5IExpbmgiLCJwaG9uZU51bWJlciI6Iis4NDkwMTIzNDU2NyIsInJvbGVJZCI6IjY5MzUzNzU1MDYxNzU5ZjA0ZjRmZGExNiIsInJvbGVOYW1lIjoiYWRtaW4iLCJwZXJtaXNzaW9ucyI6WyIqIl0sImlhdCI6MTc2NTA5OTI2MCwiZXhwIjoxNzY1MTAwMTYwfQ.bhTvtX5-NhPIa3tphDHhf-mTA4Ocy2gc3suhgmMdPqM
Accept: application/json